"""add user permissions and metadata

Revision ID: dd246f265ede
Revises: dbb0eae5d551
Create Date: 2025-02-09 20:42:50.515264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd246f265ede'
down_revision: Union[str, None] = 'dbb0eae5d551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('permissions', postgresql.ARRAY(sa.String()), nullable=False))
    op.add_column('users', sa.Column('metadata_info', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'metadata_info')
    op.drop_column('users', 'permissions')
    # ### end Alembic commands ###
