"""force logout

Revision ID: 3749323487a7
Revises: b4a0176e37fa
Create Date: 2025-02-23 02:26:49.736943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3749323487a7'
down_revision: Union[str, None] = 'b4a0176e37fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('use_token_since', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'use_token_since')
    # ### end Alembic commands ###
